# Generated by Django 4.1.7 on 2023-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='', max_length=200)),
                ('contact_message', models.TextField(default='', max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_cat',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_desc',
            field=models.TextField(default='', max_length=9000),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_name',
            field=models.TextField(default='', max_length=300),
        ),
    ]
