# Generated by Django 4.1.7 on 2023-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_reviewdata_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='reviewer_name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
