# Generated by Django 4.1.7 on 2023-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_reviewdata_reviewer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactData',
        ),
    ]
